export const TABLE_DATA_COMPLETED = 'TABLE_DATA_COMPLETED';
export const TABLE_DATA_UPDATED = 'TABLE_DATA_UPDATED';
export const FETCH_TABULAR_DATA = 'FETCH_TABULAR_DATA';
export const INITIALIZE_TABLE = 'INITIALIZE_TABLE';
export const FETCH_PAGINATED_DATA = 'FETCH_PAGINATED_DATA';
export const REMOVE_TABLE = 'REMOVE_TABLE';
