export const FETCH_TIMELINE_DATA = 'FETCH_TIMELINE_DATA';
export const INITIALIZE_TIMELINE = 'INITIALIZE_TIMELINE';
export const CREATE_TIMELINE_CONTENT = 'CREATE_TIMELINE_CONTENT';
export const REMOVE_TIMELINE = 'REMOVE_TIMELINE';
